#!/usr/bin/python3

from flask import Flask
from flask import render_template
from flask import request
from flask_cors import CORS, cross_origin
import smbus
from lcd_i2c import *

from configparser import ConfigParser

#Read config.ini file
config_object = ConfigParser()
config_object.read("config.ini")
slotparkir=info["slot"]

lcd_init()
lcd_string("TMDSpark System", LCD_LINE_1)
lcd_string("www.tmdspark.com", LCD_LINE_2)

app = Flask(__name__)
cors = CORS(app)



app.config['CORS_HEADERS'] = 'Content-Type'


def tambah_slots(x):
    y = x + 1
    return y

@app.route("/")
@cross_origin()
def helloWorld():
    return "Hello, selamat datang!"


@app.route("/slot")
def keluar():
    currentslots = tambah_slots(slotparkir)
    lcd_string('Parkiran Kosong', LCD_LINE_1)
    lcd_string(str(currentslots) + ' Slot(s)', LCD_LINE_2)
    return "Slot Bertambah"


#tambahkan slot + 1 dan edit file config
slotparkir = int(slotparkir) + 1
info["slot"]=str(slotparkir)
with open('config.ini', 'w') as conf:
    config_object.write(conf)


if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8800, debug=True)
